// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:

        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2neyCZmDa_iNBsbFtJewHOCG5W-InJXQ',
    appId: '1:454093952027:web:bc2183faccc7bf75a454be',
    messagingSenderId: '454093952027',
    projectId: 'w4-khomsan03',
    authDomain: 'w4-khomsan03.firebaseapp.com',
    storageBucket: 'w4-khomsan03.firebasestorage.app',
    measurementId: 'G-J5HPWNJFGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy2Xr7TMHfkgvTgk7q2bDW7V4Uv3dxwV4',
    appId: '1:454093952027:android:58e1cf416cd9bfb3a454be',
    messagingSenderId: '454093952027',
    projectId: 'w4-khomsan03',
    storageBucket: 'w4-khomsan03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVRz73dGhCDfZd09DfZc60NsCnAMLHZ68',
    appId: '1:454093952027:ios:68cb2f046fc52fb4a454be',
    messagingSenderId: '454093952027',
    projectId: 'w4-khomsan03',
    storageBucket: 'w4-khomsan03.firebasestorage.app',
    iosBundleId: 'com.example.w4khomsan',
  );
}
